name: ALM Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *' # Scheduled at 3 AM daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Deploy Solution and Power BI Reports
      run: npm run deploy

    - name: Migrate Data
      run: npm run migrate-data
